// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFB2XWUWHX0mrri3XL6erfNTkm1ZP4pxk',
    appId: '1:307237015335:web:e3f731b888e022389fa302',
    messagingSenderId: '307237015335',
    projectId: 'project-denning',
    authDomain: 'project-denning.firebaseapp.com',
    storageBucket: 'project-denning.appspot.com',
    measurementId: 'G-HWHQ1LW75H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSY6hS_lxoihHfBS2-hwm90xFbjSS-Qwg',
    appId: '1:307237015335:android:870b91d245b280589fa302',
    messagingSenderId: '307237015335',
    projectId: 'project-denning',
    storageBucket: 'project-denning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJYXaFr9d1m5dx0Ch1jBFJnaWmrrSO-I',
    appId: '1:307237015335:ios:75fcd134854a10419fa302',
    messagingSenderId: '307237015335',
    projectId: 'project-denning',
    storageBucket: 'project-denning.appspot.com',
    iosClientId: '307237015335-6ef4mgp3gu0sjt0d3qiar95schjd9k4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.denning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaJYXaFr9d1m5dx0Ch1jBFJnaWmrrSO-I',
    appId: '1:307237015335:ios:75fcd134854a10419fa302',
    messagingSenderId: '307237015335',
    projectId: 'project-denning',
    storageBucket: 'project-denning.appspot.com',
    iosClientId: '307237015335-6ef4mgp3gu0sjt0d3qiar95schjd9k4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.denning',
  );
}
